### ISSUE TITLE
Naive question on interpretation of README.md

### ISSUE THREAD

**Issue by claczny** [sirselim/guppy_parameter_optimiser#1]
Hi @sirselim,

thanks a lot for sharing this!

Just to see if I get that right: is the fastest FAST model config "only" about twice as fast as the fastest HAC model config?

`fast` w/ 768 chunks per runner
```
param_sweep_test/guppy_fast_768.out:chunks per runner:  768
param_sweep_test/guppy_fast_768.out:samples/s: 3.36026e+07
```

vs. 

`hac` w/ 1024 chunks per runner
```
param_sweep_hac/guppy_hac_1024.out:chunks per runner:  1024
param_sweep_hac/guppy_hac_1024.out:samples/s: 1.38832e+07
```

?

Thank you!

Best,

Cedric

**Comment by sirselim** [comment]
Hi @claczny,

No problem at all.

Yes you are interpreting that correctly. I'm not sure if you have come across some of my other benchmarking work, but the below picture demonstrates some really interesting observations about the models (fast, hac, sup):

![image](https://user-images.githubusercontent.com/5932864/154368145-d4808071-c8f8-4728-910b-53791a0dd899.png)

The first is that FAST performance appears to be directly related to the amount of CUDA cores a GPU has. That's why you see the RTX3080Ti (~10,500 cores) massively out performing cards like the A100 (which has around 6000 cores). But then as we know, the HAC and SUP models can scale with GPU RAM so you start to see the tuned/optimised performance of those cards close the gap between them and the FAST model.

The testing results for this repository were done on a Titan RTX with 24GB of RAM, hence the ability to reall increase the performance of that HAC model and bring it to within ~2x less that of FAST.

Does this help? I'm always happy to chat!

Cheers, 
  - Miles

**Comment by claczny** [comment]
Hi @sirselim 

I am not intricately familiar, but am following your posts when I can :)

This information helps very much!
Thank you also for the table!
I guess, I need to find some time to give your script a try on one of our GPU nodes on the HPC, just to see what the performance comparison there would be.

Best,

Cedric
